// <auto-generated />
using GarageApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GarageApp.Data.Migrations
{
    [DbContext(typeof(GarageAppDbContext))]
    [Migration("20260918165825_SeedGaragesAndCars")]
    partial class SeedGaragesAndCars
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GarageApp.Data.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarType")
                        .HasColumnType("int");

                    b.Property<int>("GarageId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int?>("ProductionMonth")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GarageId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarType = 1,
                            GarageId = 1,
                            IsAvailable = true,
                            Make = "Toyota",
                            Model = "Corolla",
                            ProductionMonth = 3,
                            Year = 2018
                        },
                        new
                        {
                            Id = 2,
                            CarType = 1,
                            GarageId = 1,
                            IsAvailable = true,
                            Make = "Honda",
                            Model = "Civic",
                            ProductionMonth = 5,
                            Year = 2020
                        },
                        new
                        {
                            Id = 3,
                            CarType = 0,
                            GarageId = 2,
                            IsAvailable = false,
                            Make = "Ford",
                            Model = "Focus",
                            Year = 2016
                        },
                        new
                        {
                            Id = 4,
                            CarType = 6,
                            GarageId = 3,
                            IsAvailable = true,
                            Make = "BMW",
                            Model = "Z4",
                            ProductionMonth = 7,
                            Year = 2019
                        },
                        new
                        {
                            Id = 5,
                            CarType = 2,
                            GarageId = 2,
                            IsAvailable = true,
                            Make = "Audi",
                            Model = "A5",
                            ProductionMonth = 11,
                            Year = 2021
                        },
                        new
                        {
                            Id = 6,
                            CarType = 4,
                            GarageId = 3,
                            IsAvailable = false,
                            Make = "Volkswagen",
                            Model = "Touran",
                            ProductionMonth = 2,
                            Year = 2015
                        },
                        new
                        {
                            Id = 7,
                            CarType = 8,
                            GarageId = 1,
                            IsAvailable = true,
                            Make = "Mercedes",
                            Model = "GLE",
                            ProductionMonth = 9,
                            Year = 2022
                        },
                        new
                        {
                            Id = 8,
                            CarType = 3,
                            GarageId = 2,
                            IsAvailable = true,
                            Make = "Fiat",
                            Model = "500",
                            ProductionMonth = 6,
                            Year = 2014
                        });
                });

            modelBuilder.Entity("GarageApp.Data.Models.Garage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Garages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Central City",
                            Name = "Central City Garage"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Riverside",
                            Name = "Riverside Motors"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Mountainview",
                            Name = "Mountainview Auto"
                        });
                });

            modelBuilder.Entity("GarageApp.Data.Models.Car", b =>
                {
                    b.HasOne("GarageApp.Data.Models.Garage", "Garage")
                        .WithMany("Cars")
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garage");
                });

            modelBuilder.Entity("GarageApp.Data.Models.Garage", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
