// <auto-generated />
using System;
using EventManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventManager.Data.Migrations
{
    [DbContext(typeof(EventManagerDbContext))]
    partial class EventManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventManager.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Conference"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Workshop"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Seminar"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Training"
                        });
                });

            modelBuilder.Entity("EventManager.Data.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Description = "In this workshop will be discussed the fundamentals of ASP.NET",
                            EndDate = new DateTime(2026, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxParticipants = 12,
                            StartDate = new DateTime(2026, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "ASP.NET Workshop"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "A conference covering the fundamentals of ASP.NET Core MVC",
                            EndDate = new DateTime(2026, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxParticipants = 150,
                            StartDate = new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "ASP.NET Core Conference"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Learn all the basics of web design in just 2 hours!",
                            EndDate = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxParticipants = 35,
                            StartDate = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Web design seminar"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "Become a marleyan warrior and defeat our enemies",
                            EndDate = new DateTime(2030, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxParticipants = 10,
                            StartDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Marleyan training"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            Description = "Join the scout regiment to save the people from the titans",
                            EndDate = new DateTime(2031, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxParticipants = 50,
                            StartDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Scout regiment"
                        });
                });

            modelBuilder.Entity("EventManager.Data.Models.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("ParticipantName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("EventManager.Data.Models.Event", b =>
                {
                    b.HasOne("EventManager.Data.Models.Category", "Category")
                        .WithMany("Events")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EventManager.Data.Models.Registration", b =>
                {
                    b.HasOne("EventManager.Data.Models.Event", "Event")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventManager.Data.Models.Category", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("EventManager.Data.Models.Event", b =>
                {
                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
